package com.github.theopitsihue.stise_springroll.utilities;

import com.github.theopitsihue.stise_springroll.repository.StoreRepository;
import org.aspectj.runtime.reflect.Factory;

import java.util.function.Function;
import java.util.function.Supplier;

public class Utils {
    /// Creates a URL-friendly string (SLUG) from a name. Does NOT check uniqueness!!!
    public static String toSlug(String name) {
        return name.toLowerCase()
                .replaceAll("[^a-z0-9]+", "-")
                .replaceAll("(^-|-$)", "");
    }

    /// Will create a unique SLUG by adding an increment number to the end of a store's autogenerated slug name
    /// Usage: String slug = generateUniqueSlug(entry.getName(), s -> storeRepository.existsBySlug(s));
    public static String generateUniqueSlug(String name, Function<String, Boolean> existsInRepo) {
        String baseSlug = toSlug(name); // convert name to a URL-friendly slug
        String slug = baseSlug;
        int counter = 1;

        while (existsInRepo.apply(slug)) {
            slug = baseSlug + "-" + counter++;
        }
        return slug;
    }
}